# Changes here will be overwritten by Copier
_commit: v0.8.2
_src_path: https://github.com/fohte/generic-boilerplate
auto_merge_release_pr: false
description: '@fohte''s personal monorepo of shared HTTP API contract packages'
is_public: true
project_name: contracts
release_type: node
repo_language: en
type: base
use_release_please: true
