issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte@11088009/contracts@1243002152:ref:refs/heads/.+$
claim_pattern:
  job_workflow_ref: ^fohte/contracts/\.github/workflows/test\.yml@[^@]+$
permissions:
  contents: write
